# Exercicios *Args, **kwargs, Apply e Lambda

In [69]:
import pandas as pd 
import numpy as np 

# Definindo a semente do gerador de números aleatórios para garantir reprodutibilidade 
np.random.seed(27) 

# Criando DataFrame 1 - Informações de vendas 
df_vendas = pd.DataFrame({ 
'ID_Venda': range(1, 31),  # Criando IDs únicos para cada venda (de 1 a 30) 
'Produto': np.random.choice(['Camisa', 'Calça', 'Tenis', 'Bone'], 30),  
# Produto vendido 
'Valor': np.random.uniform(50, 300, 30).round(2),  # Preço da venda 
'Quantidade': np.random.randint(1, 5, 30),  # Quantidade vendida 
'ID_Cliente': np.random.randint(1, 31, 30),  # Associando aleatoriamente um cliente à venda 
'ID_Funcionario': np.random.randint(1, 31, 30)  # Associando aleatoriamente um funcionário à venda 
}) 

# Lista de nomes para clientes 
nomes_clientes = [ 
'Lucas', 'Mariana', 'Carlos', 'Fernanda', 'Pedro', 'Ana', 'Rafael', 
'Juliana', 'Bruno', 'Camila', 
'Gustavo', 'Isabela', 'Thiago', 'Patricia', 'Felipe', 'Larissa', 
'Andre', 'Vanessa', 'Diego', 'Carla', 
'Ricardo', 'Natalia', 'Fabio', 'Bianca', 'Eduardo', 'Tatiane', 
'Leonardo', 'Aline', 'Joao', 'Leticia' ] 

# Criando DataFrame 2 - Informações de clientes 
df_clientes = pd.DataFrame({ 
'ID_Cliente': range(1, 31),  # Criando IDs únicos para os clientes (de 1 a 30) 
'Nome_Cliente': nomes_clientes,  # Nomes dos clientes 
'Idade': np.random.randint(18, 60, 30),  # Idade dos clientes 
'Cidade': np.random.choice(['Recife', 'Caruaru', 'Maceio', 'Joao Pessoa', 'Natal'], 30)  # Cidade dos clientes 
}) 

# Lista de nomes para funcionários 
nomes_funcionarios = [ 
'Roberto', 'Cristina', 'Fernando', 'Beatriz', 'Mateus', 'Sofia', 
'Daniel', 'Alessandra', 'Jose', 'Paula', 
'Antonio', 'Debora', 'Renato', 'Simone', 'Gabriel', 'Eliane', 'Cesar', 
'Adriana', 'Marcelo', 'Veronica', 
'Sergio', 'Regina', 'Alexandre', 'Claudia', 'Vinicius', 'Sandra', 
'Hugo', 'Renata', 'Paulo', 'Monica' ] 

# Criando DataFrame 3 - Informações de funcionários 
df_funcionarios = pd.DataFrame({ 
'ID_Funcionario': range(1, 31),  # Criando IDs únicos para os funcionários (de 1 a 30) 
'Nome_Funcionario': nomes_funcionarios,  # Nomes dos funcionários 
'Cargo': np.random.choice(['Vendedor', 'Gerente', 'Caixa', 'Repositor'], 30),  # Cargo dos funcionários 
'Salario': np.random.uniform(1500, 5000, 30).round(2)  # Salário dos funcionários 
})

# Ex 1
Use ´apply´ para calcular o valor total de cada venda no DataFrame ‘df_vendas’ (Valor * Quantidade).

In [70]:
def total_venda(linha):
    calculo = linha["Valor"] * linha["Quantidade"]
    return calculo
df_vendas["Total"] = df_vendas.apply(total_venda,axis=1)
display(df_vendas.head())

   ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
0         1    Bone  131.39           2           8              27  262.78
1         2  Camisa  143.23           2           6              24  286.46
2         3  Camisa  248.43           2          23               1  496.86
3         4    Bone   87.77           3          14               3  263.31
4         5  Camisa   92.49           4          12              19  369.96

# Ex 2
Crie uma função que utilize lambda para formatar os nomes dos clientes do DataFrame ‘df_clientes’ para maiúsculas.

In [71]:
df_clientes["Nome_Cliente"] = df_clientes["Nome_Cliente"].apply(lambda x: x.upper())
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade
0            1        LUCAS     37       Recife
1            2      MARIANA     50      Caruaru
2            3       CARLOS     48        Natal
3            4     FERNANDA     54        Natal
4            5        PEDRO     46      Caruaru
5            6          ANA     23       Maceio
6            7       RAFAEL     26  Joao Pessoa
7            8      JULIANA     36       Maceio
8            9        BRUNO     59       Maceio
9           10       CAMILA     34       Maceio
10          11      GUSTAVO     41  Joao Pessoa
11          12      ISABELA     21  Joao Pessoa
12          13       THIAGO     39  Joao Pessoa
13          14     PATRICIA     21      Caruaru
14          15       FELIPE     29       Recife
15          16      LARISSA     50        Natal
16          17        ANDRE     35      Caruaru
17          18      VANESSA     41      Caruaru
18          19        DIEGO     26      Caruaru
19          20        CARLA     31       Maceio
20          21      RICARDO     57  Joao Pessoa
21          22      NATALIA     40        Natal
22          23        FABIO     40       Recife
23          24       BIANCA     46        Natal
24          25      EDUARDO     48      Caruaru
25          26      TATIANE     44      Caruaru
26          27     LEONARDO     38       Maceio
27          28        ALINE     31      Caruaru
28          29         JOAO     31        Natal
29          30      LETICIA     22        Natal

# Ex 3
Utilize apply para categorizar os clientes do DataFrame ‘df_clientes’ em ‘Jovem’ (idade < 30) e ‘Adulto’ (idade >= 30).

In [72]:
def define_faixa_etaria(Idade):
    if Idade < 30:
        faixa_etaria = "Jovem"
    elif Idade >= 30:
        faixa_etaria = "Adulto"
    return faixa_etaria
df_clientes["faixa_etaria"] = df_clientes["Idade"].apply(define_faixa_etaria)
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade faixa_etaria
0            1        LUCAS     37       Recife       Adulto
1            2      MARIANA     50      Caruaru       Adulto
2            3       CARLOS     48        Natal       Adulto
3            4     FERNANDA     54        Natal       Adulto
4            5        PEDRO     46      Caruaru       Adulto
5            6          ANA     23       Maceio        Jovem
6            7       RAFAEL     26  Joao Pessoa        Jovem
7            8      JULIANA     36       Maceio       Adulto
8            9        BRUNO     59       Maceio       Adulto
9           10       CAMILA     34       Maceio       Adulto
10          11      GUSTAVO     41  Joao Pessoa       Adulto
11          12      ISABELA     21  Joao Pessoa        Jovem
12          13       THIAGO     39  Joao Pessoa       Adulto
13          14     PATRICIA     21      Caruaru        Jovem
14          15       FELIPE     29       Recife        Jovem
15          16      LARISSA     50        Natal       Adulto
16          17        ANDRE     35      Caruaru       Adulto
17          18      VANESSA     41      Caruaru       Adulto
18          19        DIEGO     26      Caruaru        Jovem
19          20        CARLA     31       Maceio       Adulto
20          21      RICARDO     57  Joao Pessoa       Adulto
21          22      NATALIA     40        Natal       Adulto
22          23        FABIO     40       Recife       Adulto
23          24       BIANCA     46        Natal       Adulto
24          25      EDUARDO     48      Caruaru       Adulto
25          26      TATIANE     44      Caruaru       Adulto
26          27     LEONARDO     38       Maceio       Adulto
27          28        ALINE     31      Caruaru       Adulto
28          29         JOAO     31        Natal       Adulto
29          30      LETICIA     22        Natal        Jovem

In [73]:
#opção com lambda
df_clientes["faixa_etaria"] = df_clientes["Idade"].apply(lambda x: "Jovem" if x < 30 else "Adulto")
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade faixa_etaria
0            1        LUCAS     37       Recife       Adulto
1            2      MARIANA     50      Caruaru       Adulto
2            3       CARLOS     48        Natal       Adulto
3            4     FERNANDA     54        Natal       Adulto
4            5        PEDRO     46      Caruaru       Adulto
5            6          ANA     23       Maceio        Jovem
6            7       RAFAEL     26  Joao Pessoa        Jovem
7            8      JULIANA     36       Maceio       Adulto
8            9        BRUNO     59       Maceio       Adulto
9           10       CAMILA     34       Maceio       Adulto
10          11      GUSTAVO     41  Joao Pessoa       Adulto
11          12      ISABELA     21  Joao Pessoa        Jovem
12          13       THIAGO     39  Joao Pessoa       Adulto
13          14     PATRICIA     21      Caruaru        Jovem
14          15       FELIPE     29       Recife        Jovem
15          16      LARISSA     50        Natal       Adulto
16          17        ANDRE     35      Caruaru       Adulto
17          18      VANESSA     41      Caruaru       Adulto
18          19        DIEGO     26      Caruaru        Jovem
19          20        CARLA     31       Maceio       Adulto
20          21      RICARDO     57  Joao Pessoa       Adulto
21          22      NATALIA     40        Natal       Adulto
22          23        FABIO     40       Recife       Adulto
23          24       BIANCA     46        Natal       Adulto
24          25      EDUARDO     48      Caruaru       Adulto
25          26      TATIANE     44      Caruaru       Adulto
26          27     LEONARDO     38       Maceio       Adulto
27          28        ALINE     31      Caruaru       Adulto
28          29         JOAO     31        Natal       Adulto
29          30      LETICIA     22        Natal        Jovem

# Ex 4
Use apply para converter os salários dos funcionários do DataFrame ‘df_funcionarios’ de Reais para Dólares (cotação fictícia).

In [74]:
df_funcionarios["Salario"] = df_funcionarios["Salario"].apply(lambda x: x / 5.21).round(2)
display(df_funcionarios.head())

   ID_Funcionario Nome_Funcionario      Cargo  Salario
0               1          Roberto    Gerente   946.43
1               2         Cristina    Gerente   499.09
2               3         Fernando  Repositor   506.34
3               4          Beatriz  Repositor   297.66
4               5           Mateus    Gerente   376.56

# Ex 5
Crie uma função que utilize *args para calcular a média dos valores da coluna ‘Valor’ do DataFrame ‘df_vendas’.

In [75]:
def media_valor(*args):
    soma = sum(args)
    quantidade = len(args)
    return soma / quantidade
resultado = media_valor(*df_vendas["Valor"])
print(f"a Média dos valores é: {resultado:.2f}")

a Média dos valores é: 161.14

# Ex 6
Utilize **kwargs para criar uma função que filtre produtos específicos no DataFrame ‘df_vendas’.

In [76]:
def filtro_produtos(**kwargs):
    df_filtrado = df_vendas.copy()

    for coluna, valor in kwargs.items():
        df_filtrado = df_filtrado[df_filtrado[coluna] == valor]
    return df_filtrado
resultado1 = filtro_produtos(Produto="Camisa")
display(resultado1)
resultado2 = filtro_produtos(Produto = "Camisa", Quantidade = 2)
display(resultado2)

    ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
1          2  Camisa  143.23           2           6              24  286.46
2          3  Camisa  248.43           2          23               1  496.86
4          5  Camisa   92.49           4          12              19  369.96
5          6  Camisa   70.29           3           3              23  210.87
7          8  Camisa  245.82           3          16               7  737.46
19        20  Camisa  233.99           3          23               1  701.97
28        29  Camisa   53.41           1           3               4   53.41

   ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
1         2  Camisa  143.23           2           6              24  286.46
2         3  Camisa  248.43           2          23               1  496.86

# Ex 7
Aplique lambda para calcular um bônus de 10% para os funcionários do DataFrame ‘df_funcionarios’ e crie uma nova coluna com os valores corrigidos.

In [77]:
df_funcionarios["salario_corridigo"] = df_funcionarios["Salario"].apply(lambda x: x * (1 + 10/100)).round(2)
display(df_funcionarios)

    ID_Funcionario Nome_Funcionario      Cargo  Salario  salario_corridigo
0                1          Roberto    Gerente   946.43            1041.07
1                2         Cristina    Gerente   499.09             549.00
2                3         Fernando  Repositor   506.34             556.97
3                4          Beatriz  Repositor   297.66             327.43
4                5           Mateus    Gerente   376.56             414.22
5                6            Sofia  Repositor   769.38             846.32
6                7           Daniel      Caixa   820.66             902.73
7                8       Alessandra      Caixa   743.21             817.53
8                9             Jose    Gerente   678.08             745.89
9               10            Paula   Vendedor   698.03             767.83
10              11          Antonio  Repositor   866.87             953.56
11              12           Debora    Gerente   376.72             414.39
12              13           Renato  Repositor   317.94             349.73
13              14           Simone      Caixa   612.88             674.17
14              15          Gabriel      Caixa   521.07             573.18
15              16           Eliane   Vendedor   724.27             796.70
16              17            Cesar      Caixa   539.98             593.98
17              18          Adriana   Vendedor   809.96             890.96
18              19          Marcelo  Repositor   768.55             845.40
19              20         Veronica    Gerente   558.53             614.38
20              21           Sergio  Repositor   808.64             889.50
21              22           Regina   Vendedor   958.87            1054.76
22              23        Alexandre   Vendedor   868.72             955.59
23              24          Claudia      Caixa   939.32            1033.25
24              25         Vinicius   Vendedor   522.34             574.57
25              26           Sandra    Gerente   658.20             724.02
26              27             Hugo  Repositor   736.14             809.75
27              28           Renata   Vendedor   781.72             859.89
28              29            Paulo    Gerente   829.24             912.16
29              30           Monica    Gerente   955.23            1050.75

# Ex 8
Crie uma função que utilize *args (argumentos variáveis) para somar todos os valores da coluna Valor de um DataFrame chamado df_vendas. A função deve aceitar uma quantidade variável de valores e retornar a soma de todos os valores passados.

In [78]:
display(df_vendas)
def soma_valor(*args):
    soma = sum(args)
    return soma

resultado = soma_valor(*df_vendas["Valor"])
print(f"A soma da coluna dos valores da coluna valor é R${resultado:.2f}")

    ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
0          1    Bone  131.39           2           8              27  262.78
1          2  Camisa  143.23           2           6              24  286.46
2          3  Camisa  248.43           2          23               1  496.86
3          4    Bone   87.77           3          14               3  263.31
4          5  Camisa   92.49           4          12              19  369.96
5          6  Camisa   70.29           3           3              23  210.87
6          7   Calça  126.29           3          19              20  378.87
7          8  Camisa  245.82           3          16               7  737.46
8          9   Calça   90.73           2          29              16  181.46
9         10   Calça   67.66           3          28              18  202.98
10        11   Calça  225.27           2          28               5  450.54
11        12   Tenis   95.24           1           1              29   95.24
12        13    Bone  199.73           4          11              18  798.92
13        14    Bone  153.82           4          12              25  615.28
14        15   Tenis  178.39           4          17              18  713.56
15        16   Calça  105.16           1           4               3  105.16
16        17   Tenis  231.39           4          11              21  925.56
17        18   Tenis  262.36           3          11              19  787.08
18        19   Calça  282.22           2          22              13  564.44
19        20  Camisa  233.99           3          23               1  701.97
20        21   Tenis  169.15           1          30               5  169.15
21        22   Tenis  173.22           1           4              16  173.22
22        23    Bone  198.63           3          30              22  595.89
23        24    Bone   69.01           1          24              16   69.01
24        25    Bone   79.37           3           7              10  238.11
25        26    Bone  291.62           1          24              23  291.62
26        27    Bone  195.83           2          20               1  391.66
27        28   Tenis   73.11           1          19               8   73.11
28        29  Camisa   53.41           1           3               4   53.41
29        30   Calça  259.23           2          20              21  518.46

A soma da coluna dos valores da coluna valor é R$4834.25

# Ex 9
Crie uma função que utilize **kwargs para calcular o valor total das vendas de produtos específicos no DataFrame df_vendas. O valor total deve ser calculado pela multiplicação do preço (Valor) pela quantidade de itens vendidos (Quantidade) para os produtos solicitados.

In [79]:
def total_por_produto(**kwargs):
    df_filtrado = df_vendas.copy()

    for coluna, valor in kwargs.items():
        df_filtrado = df_filtrado[df_filtrado[coluna] == valor]
    
    total = (df_filtrado["Valor"] * df_filtrado["Quantidade"]).sum()
    return total

venda_camisa = total_por_produto(Produto="Camisa")
print(f"O valor total vendido de Camisa é: R${venda_camisa:.2f}")

O valor total vendido de Camisa é: R$2856.99

# Ex 10
Utilize lambda para verificar quais funcionários no DataFrame ‘df_funcionarios’ possuem salários acima de R$ 3000, retornando True ou False.

In [80]:
df_funcionarios["Salario"] = df_funcionarios["Salario"].apply(lambda x: x * 5.21).round(2)
df_funcionarios["Salario"] = df_funcionarios["Salario"].apply(lambda x: x * (1 + 10/100)).round(2)

df_funcionarios["Salario_Acima3000"] = df_funcionarios["Salario"].apply(lambda x: True if x > 3000 else False)
display(df_funcionarios)

,ID_Funcionario,Nome_Funcionario,Cargo,Salario,salario_corridigo,Salario_Acima3000
0,1,Roberto,Gerente,5423.99,1041.07,True
1,2,Cristina,Gerente,2860.29,549.00,False
2,3,Fernando,Repositor,2901.83,556.97,False
3,4,Beatriz,Repositor,1705.89,327.43,False
4,5,Mateus,Gerente,2158.07,414.22,False
5,6,Sofia,Repositor,4409.32,846.32,True
6,7,Daniel,Caixa,4703.20,902.73,True
7,8,Alessandra,Caixa,4259.33,817.53,True
8,9,Jose,Gerente,3886.08,745.89,True
9,10,Paula,Vendedor,4000.41,767.83,True
10,11,Antonio,Repositor,4968.03,953.56,True
11,12,Debora,Gerente,2158.98,414.39,False
12,13,Renato,Repositor,1822.12,349.73,False
13,14,Simone,Caixa,3512.41,674.17,True
14,15,Gabriel,Caixa,2986.25,573.18,False
15,16,Eliane,Vendedor,4150.80,796.70,True
16,17,Cesar,Caixa,3094.63,593.98,True
17,18,Adriana,Vendedor,4641.88,890.96,True
18,19,Marcelo,Repositor,4404.57,845.40,True
19,20,Veronica,Gerente,3200.93,614.38,True
20,21,Sergio,Repositor,4634.31,889.50,True
21,22,Regina,Vendedor,5495.28,1054.76,True
22,23,Alexandre,Vendedor,4978.63,955.59,True
23,24,Claudia,Caixa,5383.25,1033.25,True
24,25,Vinicius,Vendedor,2993.53,574.57,False
25,26,Sandra,Gerente,3772.14,724.02,True
26,27,Hugo,Repositor,4218.82,809.75,True
27,28,Renata,Vendedor,4480.04,859.89,True
28,29,Paulo,Gerente,4752.37,912.16,True
29,30,Monica,Gerente,5474.42,1050.75,True

# ex 11
Desenvolva uma função que utilize apply para calcular o ticket médio de cada cliente no DataFrame ‘df_vendas’.

In [81]:
def ticket_medio_cliente(id_do_cliente):
    vendas_cliente = df_vendas[df_vendas["ID_Cliente"] == id_do_cliente]
    return vendas_cliente["Total"].mean()

df_vendas["Ticket_Medio_Cliente"] = df_vendas["ID_Cliente"].apply(ticket_medio_cliente)

display(df_vendas[["ID_Cliente" ,"Ticket_Medio_Cliente"]]
        .drop_duplicates()
        .sort_values(by="Ticket_Medio_Cliente", ascending=False))

    ID_Cliente  Ticket_Medio_Cliente
12          11            837.186667
7           16            737.460000
14          17            713.560000
2           23            599.415000
18          22            564.440000
4           12            492.620000
26          20            455.060000
20          30            382.520000
9           28            326.760000
1            6            286.460000
3           14            263.310000
0            8            262.780000
24           7            238.110000
6           19            225.990000
8           29            181.460000
23          24            180.315000
15           4            139.190000
5            3            132.140000
11           1             95.240000

# Ex 12
Use **kwargs para filtrar os dados do DataFrame ‘df_funcionarios’ por cargos específicos

In [82]:
def filtro_cargo(**kwargs):
    df_filtrado_cargo = df_funcionarios.copy()
    for coluna, valor in kwargs.items():
        df_filtrado_cargo = df_filtrado_cargo[df_filtrado_cargo[coluna] == valor]
    return df_filtrado_cargo
resultado = filtro_cargo(Cargo= "Gerente")
display(resultado)

,ID_Funcionario,Nome_Funcionario,Cargo,Salario,salario_corridigo,Salario_Acima3000
0,1,Roberto,Gerente,5423.99,1041.07,True
1,2,Cristina,Gerente,2860.29,549.00,False
4,5,Mateus,Gerente,2158.07,414.22,False
8,9,Jose,Gerente,3886.08,745.89,True
11,12,Debora,Gerente,2158.98,414.39,False
19,20,Veronica,Gerente,3200.93,614.38,True
25,26,Sandra,Gerente,3772.14,724.02,True
28,29,Paulo,Gerente,4752.37,912.16,True
29,30,Monica,Gerente,5474.42,1050.75,True

# Ex 13
Utilize apply para calcular o total gasto por cada cliente (somando o valor total das vendas de cada cliente). Crie uma nova coluna no ‘df_clientes’ com o total gasto por cliente.

In [83]:
def total_gasto_cliente(id_cliente):
    vendas_especificas = df_vendas[df_vendas["ID_Cliente"] == id_cliente]
    total_vendas_especificas = (vendas_especificas["Valor"] * vendas_especificas["Quantidade"]).sum()
    return total_vendas_especificas

df_clientes["Total_Gasto"] = df_clientes["ID_Cliente"].apply(total_gasto_cliente)
display(df_clientes.sort_values(by="Total_Gasto", ascending=False))

    ID_Cliente Nome_Cliente  Idade       Cidade faixa_etaria  Total_Gasto
10          11      GUSTAVO     41  Joao Pessoa       Adulto      2511.56
22          23        FABIO     40       Recife       Adulto      1198.83
11          12      ISABELA     21  Joao Pessoa        Jovem       985.24
19          20        CARLA     31       Maceio       Adulto       910.12
29          30      LETICIA     22        Natal        Jovem       765.04
15          16      LARISSA     50        Natal       Adulto       737.46
16          17        ANDRE     35      Caruaru       Adulto       713.56
27          28        ALINE     31      Caruaru       Adulto       653.52
21          22      NATALIA     40        Natal       Adulto       564.44
18          19        DIEGO     26      Caruaru        Jovem       451.98
23          24       BIANCA     46        Natal       Adulto       360.63
5            6          ANA     23       Maceio        Jovem       286.46
3            4     FERNANDA     54        Natal       Adulto       278.38
2            3       CARLOS     48        Natal       Adulto       264.28
13          14     PATRICIA     21      Caruaru        Jovem       263.31
7            8      JULIANA     36       Maceio       Adulto       262.78
6            7       RAFAEL     26  Joao Pessoa        Jovem       238.11
28          29         JOAO     31        Natal       Adulto       181.46
0            1        LUCAS     37       Recife       Adulto        95.24
1            2      MARIANA     50      Caruaru       Adulto         0.00
8            9        BRUNO     59       Maceio       Adulto         0.00
4            5        PEDRO     46      Caruaru       Adulto         0.00
12          13       THIAGO     39  Joao Pessoa       Adulto         0.00
9           10       CAMILA     34       Maceio       Adulto         0.00
14          15       FELIPE     29       Recife        Jovem         0.00
17          18      VANESSA     41      Caruaru       Adulto         0.00
20          21      RICARDO     57  Joao Pessoa       Adulto         0.00
24          25      EDUARDO     48      Caruaru       Adulto         0.00
25          26      TATIANE     44      Caruaru       Adulto         0.00
26          27     LEONARDO     38       Maceio       Adulto         0.00

# Ex 14
Crie uma função que utilize apply para calcular o valor médio de vendas por funcionário (considerando o número e valor de vendas realizadas por cada funcionário). Crie uma nova coluna no ‘df_funcionarios’ com a média de vendas por funcionário.

In [84]:
def calcular_media_vendas(id_funcionario):
    vendas_funcionario = df_vendas[df_vendas["ID_Funcionario"] == id_funcionario]
    if len(vendas_funcionario) == 0:
        return 0
    total_vendas_funcionario = (vendas_funcionario["Valor"] * vendas_funcionario["Quantidade"]).sum()
    media_vendas = total_vendas_funcionario / len(vendas_funcionario)
    return media_vendas

df_funcionarios["Media_Vendas"] = df_funcionarios["ID_Funcionario"].apply(calcular_media_vendas)

display(df_funcionarios.round(2).sort_values(by="Media_Vendas", ascending=False))

,ID_Funcionario,Nome_Funcionario,Cargo,Salario,salario_corridigo,Salario_Acima3000,Media_Vendas
6,7,Daniel,Caixa,4703.20,902.73,True,737.46
20,21,Sergio,Repositor,4634.31,889.50,True,722.01
24,25,Vinicius,Vendedor,2993.53,574.57,False,615.28
21,22,Regina,Vendedor,5495.28,1054.76,True,595.89
18,19,Marcelo,Repositor,4404.57,845.40,True,578.52
17,18,Adriana,Vendedor,4641.88,890.96,True,571.82
12,13,Renato,Repositor,1822.12,349.73,False,564.44
0,1,Roberto,Gerente,5423.99,1041.07,True,530.16
19,20,Veronica,Gerente,3200.93,614.38,True,378.87
4,5,Mateus,Gerente,2158.07,414.22,False,309.85
23,24,Claudia,Caixa,5383.25,1033.25,True,286.46
26,27,Hugo,Repositor,4218.82,809.75,True,262.78
22,23,Alexandre,Vendedor,4978.63,955.59,True,251.24
9,10,Paula,Vendedor,4000.41,767.83,True,238.11
2,3,Fernando,Repositor,2901.83,556.97,False,184.24
15,16,Eliane,Vendedor,4150.80,796.70,True,141.23
28,29,Paulo,Gerente,4752.37,912.16,True,95.24
7,8,Alessandra,Caixa,4259.33,817.53,True,73.11
3,4,Beatriz,Repositor,1705.89,327.43,False,53.41
5,6,Sofia,Repositor,4409.32,846.32,True,0.00
1,2,Cristina,Gerente,2860.29,549.00,False,0.00
8,9,Jose,Gerente,3886.08,745.89,True,0.00
13,14,Simone,Caixa,3512.41,674.17,True,0.00
11,12,Debora,Gerente,2158.98,414.39,False,0.00
10,11,Antonio,Repositor,4968.03,953.56,True,0.00
16,17,Cesar,Caixa,3094.63,593.98,True,0.00
14,15,Gabriel,Caixa,2986.25,573.18,False,0.00
25,26,Sandra,Gerente,3772.14,724.02,True,0.00
27,28,Renata,Vendedor,4480.04,859.89,True,0.00
29,30,Monica,Gerente,5474.42,1050.75,True,0.00

# ex 15
Utilize apply para calcular o valor total vendido por cada funcionário (somando o valor das vendas associadas a cada funcionário). Crie uma nova coluna no ‘df_funcionarios’ com o total vendido por cada funcionário.

In [89]:
def calcular_total_vendido(id_funcionario):
    vendas_funcionario = df_vendas[df_vendas["ID_Funcionario"] == id_funcionario]
    total_vendas_funcionario = (vendas_funcionario["Valor"] * vendas_funcionario["Quantidade"]).sum()
    return total_vendas_funcionario

df_funcionarios["Total_Vendido"] = df_funcionarios["ID_Funcionario"].apply(calcular_total_vendido)

display(df_funcionarios.round(2).sort_values(by="Total_Vendido", ascending=False))

,ID_Funcionario,Nome_Funcionario,Cargo,Salario,salario_corridigo,Salario_Acima3000,Media_Vendas,Total_Vendido
17,18,Adriana,Vendedor,4641.88,890.96,True,571.82,1715.46
0,1,Roberto,Gerente,5423.99,1041.07,True,530.16,1590.49
20,21,Sergio,Repositor,4634.31,889.50,True,722.01,1444.02
18,19,Marcelo,Repositor,4404.57,845.40,True,578.52,1157.04
6,7,Daniel,Caixa,4703.20,902.73,True,737.46,737.46
4,5,Mateus,Gerente,2158.07,414.22,False,309.85,619.69
24,25,Vinicius,Vendedor,2993.53,574.57,False,615.28,615.28
21,22,Regina,Vendedor,5495.28,1054.76,True,595.89,595.89
12,13,Renato,Repositor,1822.12,349.73,False,564.44,564.44
22,23,Alexandre,Vendedor,4978.63,955.59,True,251.24,502.49
15,16,Eliane,Vendedor,4150.80,796.70,True,141.23,423.69
19,20,Veronica,Gerente,3200.93,614.38,True,378.87,378.87
2,3,Fernando,Repositor,2901.83,556.97,False,184.24,368.47
23,24,Claudia,Caixa,5383.25,1033.25,True,286.46,286.46
26,27,Hugo,Repositor,4218.82,809.75,True,262.78,262.78
9,10,Paula,Vendedor,4000.41,767.83,True,238.11,238.11
28,29,Paulo,Gerente,4752.37,912.16,True,95.24,95.24
7,8,Alessandra,Caixa,4259.33,817.53,True,73.11,73.11
3,4,Beatriz,Repositor,1705.89,327.43,False,53.41,53.41
5,6,Sofia,Repositor,4409.32,846.32,True,0.00,0.00
1,2,Cristina,Gerente,2860.29,549.00,False,0.00,0.00
8,9,Jose,Gerente,3886.08,745.89,True,0.00,0.00
13,14,Simone,Caixa,3512.41,674.17,True,0.00,0.00
11,12,Debora,Gerente,2158.98,414.39,False,0.00,0.00
10,11,Antonio,Repositor,4968.03,953.56,True,0.00,0.00
16,17,Cesar,Caixa,3094.63,593.98,True,0.00,0.00
14,15,Gabriel,Caixa,2986.25,573.18,False,0.00,0.00
25,26,Sandra,Gerente,3772.14,724.02,True,0.00,0.00
27,28,Renata,Vendedor,4480.04,859.89,True,0.00,0.00
29,30,Monica,Gerente,5474.42,1050.75,True,0.00,0.00