# Exercicios *Args, **kwargs, Apply e Lambda

In [40]:
import pandas as pd 
import numpy as np 

# Definindo a semente do gerador de números aleatórios para garantir reprodutibilidade 
np.random.seed(27) 

# Criando DataFrame 1 - Informações de vendas 
df_vendas = pd.DataFrame({ 
'ID_Venda': range(1, 31),  # Criando IDs únicos para cada venda (de 1 a 30) 
'Produto': np.random.choice(['Camisa', 'Calça', 'Tenis', 'Bone'], 30),  
# Produto vendido 
'Valor': np.random.uniform(50, 300, 30).round(2),  # Preço da venda 
'Quantidade': np.random.randint(1, 5, 30),  # Quantidade vendida 
'ID_Cliente': np.random.randint(1, 31, 30),  # Associando aleatoriamente um cliente à venda 
'ID_Funcionario': np.random.randint(1, 31, 30)  # Associando aleatoriamente um funcionário à venda 
}) 

# Lista de nomes para clientes 
nomes_clientes = [ 
'Lucas', 'Mariana', 'Carlos', 'Fernanda', 'Pedro', 'Ana', 'Rafael', 
'Juliana', 'Bruno', 'Camila', 
'Gustavo', 'Isabela', 'Thiago', 'Patricia', 'Felipe', 'Larissa', 
'Andre', 'Vanessa', 'Diego', 'Carla', 
'Ricardo', 'Natalia', 'Fabio', 'Bianca', 'Eduardo', 'Tatiane', 
'Leonardo', 'Aline', 'Joao', 'Leticia' ] 

# Criando DataFrame 2 - Informações de clientes 
df_clientes = pd.DataFrame({ 
'ID_Cliente': range(1, 31),  # Criando IDs únicos para os clientes (de 1 a 30) 
'Nome_Cliente': nomes_clientes,  # Nomes dos clientes 
'Idade': np.random.randint(18, 60, 30),  # Idade dos clientes 
'Cidade': np.random.choice(['Recife', 'Caruaru', 'Maceio', 'Joao Pessoa', 'Natal'], 30)  # Cidade dos clientes 
}) 

# Lista de nomes para funcionários 
nomes_funcionarios = [ 
'Roberto', 'Cristina', 'Fernando', 'Beatriz', 'Mateus', 'Sofia', 
'Daniel', 'Alessandra', 'Jose', 'Paula', 
'Antonio', 'Debora', 'Renato', 'Simone', 'Gabriel', 'Eliane', 'Cesar', 
'Adriana', 'Marcelo', 'Veronica', 
'Sergio', 'Regina', 'Alexandre', 'Claudia', 'Vinicius', 'Sandra', 
'Hugo', 'Renata', 'Paulo', 'Monica' ] 

# Criando DataFrame 3 - Informações de funcionários 
df_funcionarios = pd.DataFrame({ 
'ID_Funcionario': range(1, 31),  # Criando IDs únicos para os funcionários (de 1 a 30) 
'Nome_Funcionario': nomes_funcionarios,  # Nomes dos funcionários 
'Cargo': np.random.choice(['Vendedor', 'Gerente', 'Caixa', 'Repositor'], 30),  # Cargo dos funcionários 
'Salario': np.random.uniform(1500, 5000, 30).round(2)  # Salário dos funcionários 
})

# Ex 1
Use ´apply´ para calcular o valor total de cada venda no DataFrame ‘df_vendas’ (Valor * Quantidade).

In [41]:
def total_venda(linha):
    calculo = linha["Valor"] * linha["Quantidade"]
    return calculo
df_vendas["Total"] = df_vendas.apply(total_venda,axis=1)
display(df_vendas.head())

   ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
0         1    Bone  131.39           2           8              27  262.78
1         2  Camisa  143.23           2           6              24  286.46
2         3  Camisa  248.43           2          23               1  496.86
3         4    Bone   87.77           3          14               3  263.31
4         5  Camisa   92.49           4          12              19  369.96

# Ex 2
Crie uma função que utilize lambda para formatar os nomes dos clientes do DataFrame ‘df_clientes’ para maiúsculas.

In [42]:
df_clientes["Nome_Cliente"] = df_clientes["Nome_Cliente"].apply(lambda x: x.upper())
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade
0            1        LUCAS     37       Recife
1            2      MARIANA     50      Caruaru
2            3       CARLOS     48        Natal
3            4     FERNANDA     54        Natal
4            5        PEDRO     46      Caruaru
5            6          ANA     23       Maceio
6            7       RAFAEL     26  Joao Pessoa
7            8      JULIANA     36       Maceio
8            9        BRUNO     59       Maceio
9           10       CAMILA     34       Maceio
10          11      GUSTAVO     41  Joao Pessoa
11          12      ISABELA     21  Joao Pessoa
12          13       THIAGO     39  Joao Pessoa
13          14     PATRICIA     21      Caruaru
14          15       FELIPE     29       Recife
15          16      LARISSA     50        Natal
16          17        ANDRE     35      Caruaru
17          18      VANESSA     41      Caruaru
18          19        DIEGO     26      Caruaru
19          20        CARLA     31       Maceio
20          21      RICARDO     57  Joao Pessoa
21          22      NATALIA     40        Natal
22          23        FABIO     40       Recife
23          24       BIANCA     46        Natal
24          25      EDUARDO     48      Caruaru
25          26      TATIANE     44      Caruaru
26          27     LEONARDO     38       Maceio
27          28        ALINE     31      Caruaru
28          29         JOAO     31        Natal
29          30      LETICIA     22        Natal

# Ex 3
Utilize apply para categorizar os clientes do DataFrame ‘df_clientes’ em ‘Jovem’ (idade < 30) e ‘Adulto’ (idade >= 30).

In [43]:
def define_faixa_etaria(Idade):
    if Idade < 30:
        faixa_etaria = "Jovem"
    elif Idade >= 30:
        faixa_etaria = "Adulto"
    return faixa_etaria
df_clientes["faixa_etaria"] = df_clientes["Idade"].apply(define_faixa_etaria)
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade faixa_etaria
0            1        LUCAS     37       Recife       Adulto
1            2      MARIANA     50      Caruaru       Adulto
2            3       CARLOS     48        Natal       Adulto
3            4     FERNANDA     54        Natal       Adulto
4            5        PEDRO     46      Caruaru       Adulto
5            6          ANA     23       Maceio        Jovem
6            7       RAFAEL     26  Joao Pessoa        Jovem
7            8      JULIANA     36       Maceio       Adulto
8            9        BRUNO     59       Maceio       Adulto
9           10       CAMILA     34       Maceio       Adulto
10          11      GUSTAVO     41  Joao Pessoa       Adulto
11          12      ISABELA     21  Joao Pessoa        Jovem
12          13       THIAGO     39  Joao Pessoa       Adulto
13          14     PATRICIA     21      Caruaru        Jovem
14          15       FELIPE     29       Recife        Jovem
15          16      LARISSA     50        Natal       Adulto
16          17        ANDRE     35      Caruaru       Adulto
17          18      VANESSA     41      Caruaru       Adulto
18          19        DIEGO     26      Caruaru        Jovem
19          20        CARLA     31       Maceio       Adulto
20          21      RICARDO     57  Joao Pessoa       Adulto
21          22      NATALIA     40        Natal       Adulto
22          23        FABIO     40       Recife       Adulto
23          24       BIANCA     46        Natal       Adulto
24          25      EDUARDO     48      Caruaru       Adulto
25          26      TATIANE     44      Caruaru       Adulto
26          27     LEONARDO     38       Maceio       Adulto
27          28        ALINE     31      Caruaru       Adulto
28          29         JOAO     31        Natal       Adulto
29          30      LETICIA     22        Natal        Jovem

In [44]:
#opção com lambda
df_clientes["faixa_etaria"] = df_clientes["Idade"].apply(lambda x: "Jovem" if x < 30 else "Adulto")
display(df_clientes)

    ID_Cliente Nome_Cliente  Idade       Cidade faixa_etaria
0            1        LUCAS     37       Recife       Adulto
1            2      MARIANA     50      Caruaru       Adulto
2            3       CARLOS     48        Natal       Adulto
3            4     FERNANDA     54        Natal       Adulto
4            5        PEDRO     46      Caruaru       Adulto
5            6          ANA     23       Maceio        Jovem
6            7       RAFAEL     26  Joao Pessoa        Jovem
7            8      JULIANA     36       Maceio       Adulto
8            9        BRUNO     59       Maceio       Adulto
9           10       CAMILA     34       Maceio       Adulto
10          11      GUSTAVO     41  Joao Pessoa       Adulto
11          12      ISABELA     21  Joao Pessoa        Jovem
12          13       THIAGO     39  Joao Pessoa       Adulto
13          14     PATRICIA     21      Caruaru        Jovem
14          15       FELIPE     29       Recife        Jovem
15          16      LARISSA     50        Natal       Adulto
16          17        ANDRE     35      Caruaru       Adulto
17          18      VANESSA     41      Caruaru       Adulto
18          19        DIEGO     26      Caruaru        Jovem
19          20        CARLA     31       Maceio       Adulto
20          21      RICARDO     57  Joao Pessoa       Adulto
21          22      NATALIA     40        Natal       Adulto
22          23        FABIO     40       Recife       Adulto
23          24       BIANCA     46        Natal       Adulto
24          25      EDUARDO     48      Caruaru       Adulto
25          26      TATIANE     44      Caruaru       Adulto
26          27     LEONARDO     38       Maceio       Adulto
27          28        ALINE     31      Caruaru       Adulto
28          29         JOAO     31        Natal       Adulto
29          30      LETICIA     22        Natal        Jovem

# Ex 4
Use apply para converter os salários dos funcionários do DataFrame ‘df_funcionarios’ de Reais para Dólares (cotação fictícia).

In [45]:
df_funcionarios["Salario"] = df_funcionarios["Salario"].apply(lambda x: x / 5.21).round(2)
display(df_funcionarios.head())

   ID_Funcionario Nome_Funcionario      Cargo  Salario
0               1          Roberto    Gerente   946.43
1               2         Cristina    Gerente   499.09
2               3         Fernando  Repositor   506.34
3               4          Beatriz  Repositor   297.66
4               5           Mateus    Gerente   376.56

# Ex 5
Crie uma função que utilize *args para calcular a média dos valores da coluna ‘Valor’ do DataFrame ‘df_vendas’.

In [51]:
def media_valor(*args):
    soma = sum(args)
    quantidade = len(args)
    return soma / quantidade
resultado = media_valor(*df_vendas["Valor"])
print(f"a Média dos valores é: {resultado:.2f}")

a Média dos valores é: 161.14

# Ex 6
Utilize **kwargs para criar uma função que filtre produtos específicos no DataFrame ‘df_vendas’.

In [54]:
def filtro_produtos(**kwargs):
    df_filtrado = df_vendas.copy()

    for coluna, valor in kwargs.items():
        df_filtrado = df_filtrado[df_filtrado[coluna] == valor]
    return df_filtrado
resultado1 = filtro_produtos(Produto="Camisa")
display(resultado1)
resultado2 = filtro_produtos(Produto = "Camisa", Quantidade = 2)
display(resultado2)

    ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
1          2  Camisa  143.23           2           6              24  286.46
2          3  Camisa  248.43           2          23               1  496.86
4          5  Camisa   92.49           4          12              19  369.96
5          6  Camisa   70.29           3           3              23  210.87
7          8  Camisa  245.82           3          16               7  737.46
19        20  Camisa  233.99           3          23               1  701.97
28        29  Camisa   53.41           1           3               4   53.41

   ID_Venda Produto   Valor  Quantidade  ID_Cliente  ID_Funcionario   Total
1         2  Camisa  143.23           2           6              24  286.46
2         3  Camisa  248.43           2          23               1  496.86