# Exercicio Funções

In [39]:
import pandas as pd  # Importa a biblioteca pandas para manipulação de dados tabulares 
import numpy as np  # Importa a biblioteca numpy para operações matemáticas e manipulação de arrays 

# Definindo a semente para gerar sempre os mesmos números aleatórios 
np.random.seed(27) 

# Criando um DataFrame com colunas ID, Nome e Idade 
df_pessoas = pd.DataFrame({ 
'ID': range(1, 31),  # Coluna ID com valores de 1 a 30 
'nome': ['Alice', 'Bruno', 'Carla', 'Daniel', 'Eduarda', 'Fernando', 
'Gabriela', 'Henrique', 'Isabela', 'João', 
'Karla', 'Lucas', 'Mariana', 'Nathan', 'Olivia', 'Paulo', 'Quezia', 
'Ricardo', 'Sabrina', 'Thiago', 
'Ursula', 'Vinicius', 'William', 'Xavier', 'Yasmin', 'Zaqueu', 
'Amanda', 'Bernardo', 'Camila', 'Diego' ],  # Coluna Nome com uma lista de 30 nomes fictícios 
'idade': np.random.randint(18, 60, 30)  # Coluna Idade com valores aleatórios entre 18 e 59 
}) 

# Cria um segundo DataFrame com informações de salário e departamento 
df_funcionarios = pd.DataFrame({ 
'ID': range(1, 31),  # Coluna ID com valores de 1 a 30 
'salario': np.random.randint(3000, 10000, 30),  # Coluna Salário com valores aleatórios entre 3000 e 9999 
'departamento': np.random.choice(['TI', 'RH', 'Financeiro', 'Marketing', 'Vendas'], 30)  # Coluna Departamento com escolha aleatória entre 5 opções 
}) 

# Criando o terceiro DataFrame com a média salarial por departamento 
# Calculando a média salarial por departamento 
df_departamentos = df_funcionarios.groupby('departamento')['salario'].mean().reset_index() 

# Renomeando a coluna para 'media_salario' 
df_departamentos.rename(columns={'salario': 'media_salario'}, inplace=True)

display(df_pessoas.head())
display(df_funcionarios.head())
display(df_departamentos.head())

   ID     nome  idade
0   1    Alice     37
1   2    Bruno     26
2   3    Carla     49
3   4   Daniel     55
4   5  Eduarda     42

   ID  salario departamento
0   1     7019           RH
1   2     7741       Vendas
2   3     6498           RH
3   4     4043    Marketing
4   5     9581   Financeiro

  departamento  media_salario
0   Financeiro    6261.714286
1    Marketing    6821.714286
2           RH    7096.250000
3           TI    7363.200000
4       Vendas    7986.571429

# Ex 1
    Crie uma função que receba df_pessoas e retorne a média das idades.

In [40]:
def media_idades(df_pessoas):
    media = df_pessoas["idade"].sum() / len(df_pessoas)
    return media
print(f"A média das idades é: {media_idades(df_pessoas):.2f}")

A média das idades é: 38.87

# Ex 2
    Crie uma função que receba df_funcionarios e retorne o salário máximo e mínimo.

In [ ]:
def salario_maximo_minimo(df_funcionarios):
    maximo = df_funcionarios["salario"].max()
    minimo = df_funcionarios["salario"].min()
    return maximo, minimo

v_max, v_min = salario_maximo_minimo(df_funcionarios)
print(f"Salário máximo: R${v_max}, Salário mínimo: R${v_min}")

Salário máximo: R$9919, Salário mínimo: R$3540

# Ex 3
    Escreva uma função que filtre df_pessoas para retornar apenas pessoas acima de 42 anos.

In [ ]:
def filtrar_acima_42(df_pessoas):
    df_filtrado = df_pessoas[df_pessoas["idade"] > 42]
    return df_filtrado
resultado = filtrar_acima_42(df_pessoas)
display(resultado)

    ID      nome  idade
2    3     Carla     49
3    4    Daniel     55
5    6  Fernando     43
8    9   Isabela     51
11  12     Lucas     49
15  16     Paulo     50
19  20    Thiago     44
22  23   William     47
23  24    Xavier     52
24  25    Yasmin     57
25  26    Zaqueu     58
26  27    Amanda     51
29  30     Diego     53

# Ex 4
    Crie uma função que una df_pessoas e df_funcionarios com base na coluna 'ID'

In [ ]:
def uniao_ID(df_pessoas, df_funcionarios):
    df_unido_id = pd.merge(df_pessoas, df_funcionarios, on="ID")
    return df_unido_id
resultado = uniao_ID(df_pessoas, df_funcionarios)
display(resultado)

    ID      nome  idade  salario departamento
0    1     Alice     37     7019           RH
1    2     Bruno     26     7741       Vendas
2    3     Carla     49     6498           RH
3    4    Daniel     55     4043    Marketing
4    5   Eduarda     42     9581   Financeiro
5    6  Fernando     43     9112           RH
6    7  Gabriela     31     9295       Vendas
7    8  Henrique     20     8428    Marketing
8    9   Isabela     51     6153       Vendas
9   10      João     28     4815   Financeiro
10  11     Karla     22     8472       Vendas
11  12     Lucas     49     7487       Vendas
12  13   Mariana     37     3540   Financeiro
13  14    Nathan     33     5952           TI
14  15    Olivia     33     7381   Financeiro
15  16     Paulo     50     7681       Vendas
16  17    Quezia     39     5756           RH
17  18   Ricardo     30     5876           TI
18  19   Sabrina     21     9919           TI
19  20    Thiago     44     9720    Marketing
20  21    Ursula     30     5201   Financeiro
21  22  Vinicius     25     6551   Financeiro
22  23   William     47     9077       Vendas
23  24    Xavier     52     6874    Marketing
24  25    Yasmin     57     5866    Marketing
25  26    Zaqueu     58     5668           TI
26  27    Amanda     51     6763   Financeiro
27  28  Bernardo     20     8744    Marketing
28  29    Camila     33     9401           TI
29  30     Diego     53     4077    Marketing

# Ex 5
    Escreva uma função que adicione uma nova linha ao df_pessoas.

In [ ]:
def adicionar_pessoas(df_pessoas, ID , nome, idade):
    nova_info = {
        "ID": [ID],
        "nome": [nome],
        "idade": [idade]
    }
    df_nova_linha = pd.DataFrame(nova_info)
    df_atualizado = pd.concat([df_pessoas, df_nova_linha], ignore_index=True)
    return df_atualizado

df_pessoas = adicionar_pessoas(df_pessoas, 31, "João Luís", 22)
display(df_pessoas.tail())

    ID       nome  idade
26  27     Amanda     51
27  28   Bernardo     20
28  29     Camila     33
29  30      Diego     53
30  31  João Luís     22

# Ex 6
    Faça uma função que receba df_funcionarios e retorne o total gasto com salários.

In [ ]:
def gasto_folha_salarial(df_funcionarios):
    folha_salarial = df_funcionarios["salario"].sum()
    return folha_salarial

resultado = gasto_folha_salarial(df_funcionarios)
print(f"O tatal gasto com salário é R${resultado:,.2f}")

O tatal gasto com salário é R$212,691.00

# Ex 7
    Escreva uma função que conte quantos funcionários há em cada departamento usando df_funcionarios.

In [51]:
def quantidade_por_departamento(df_funcionarios):
    quantidade = df_funcionarios.groupby("departamento")["ID"].count()
    return quantidade
resultado = quantidade_por_departamento(df_funcionarios)
display(resultado)

departamento
Financeiro    7
Marketing     7
RH            4
TI            5
Vendas        7
Name: ID, dtype: int64

# Ex 8
Crie uma função que some os salários por departamento usando df_funcionarios.

In [54]:
def soma_salarios_departamento (df_funcionarios):
    soma = df_funcionarios.groupby("departamento")["salario"].sum().sort_values(ascending=False)
    return soma
resultado = soma_salarios_departamento(df_funcionarios)
display(resultado)

departamento
Vendas        55906
Marketing     47752
Financeiro    43832
TI            36816
RH            28385
Name: salario, dtype: int32

# Ex 9
Escreva uma função que insira uma nova coluna 'Bonus' em df_funcionarios, que seja 10% do salário.

In [58]:
def coluna_bonus(df_funcionarios):
    df_funcionarios["Bonus"] = df_funcionarios["salario"] * 10 / 100
    return df_funcionarios
df_funcionarios = coluna_bonus(df_funcionarios)
display(df_funcionarios)

    ID  salario departamento  Bonus
0    1     7019           RH  701.9
1    2     7741       Vendas  774.1
2    3     6498           RH  649.8
3    4     4043    Marketing  404.3
4    5     9581   Financeiro  958.1
5    6     9112           RH  911.2
6    7     9295       Vendas  929.5
7    8     8428    Marketing  842.8
8    9     6153       Vendas  615.3
9   10     4815   Financeiro  481.5
10  11     8472       Vendas  847.2
11  12     7487       Vendas  748.7
12  13     3540   Financeiro  354.0
13  14     5952           TI  595.2
14  15     7381   Financeiro  738.1
15  16     7681       Vendas  768.1
16  17     5756           RH  575.6
17  18     5876           TI  587.6
18  19     9919           TI  991.9
19  20     9720    Marketing  972.0
20  21     5201   Financeiro  520.1
21  22     6551   Financeiro  655.1
22  23     9077       Vendas  907.7
23  24     6874    Marketing  687.4
24  25     5866    Marketing  586.6
25  26     5668           TI  566.8
26  27     6763   Financeiro  676.3
27  28     8744    Marketing  874.4
28  29     9401           TI  940.1
29  30     4077    Marketing  407.7

# Ex 10
Faça uma função que receba df_pessoas e um nome, e retorne a idade correspondente.

In [ ]:
def idade_correspondente_nome (df_pessoas, nome):
    idade = df_pessoas[df_pessoas["nome"] == nome]["idade"].values[0]
    return idade

nome_buscado = input("Digite um nome para ser encontrado:").title()
resultado_da_busca = idade_correspondente_nome(df_pessoas, nome_buscado)
print(f"A idade de {nome_buscado} é {resultado_da_busca} anos.")

A idade de João Luís é 22 anos.

# Ex 11
Crie uma função que padronize os nomes da coluna 'nome' para letras maiusculas em df_pessoas.

In [73]:
def transforma_nomes_maiusculos(df_pessoas):
    df_pessoas["nome"] = df_pessoas["nome"].str.upper()
    return df_pessoas
df_pessoas = transforma_nomes_maiusculos(df_pessoas)
display(df_pessoas)

    ID       nome  idade
0    1      ALICE     37
1    2      BRUNO     26
2    3      CARLA     49
3    4     DANIEL     55
4    5    EDUARDA     42
5    6   FERNANDO     43
6    7   GABRIELA     31
7    8   HENRIQUE     20
8    9    ISABELA     51
9   10       JOÃO     28
10  11      KARLA     22
11  12      LUCAS     49
12  13    MARIANA     37
13  14     NATHAN     33
14  15     OLIVIA     33
15  16      PAULO     50
16  17     QUEZIA     39
17  18    RICARDO     30
18  19    SABRINA     21
19  20     THIAGO     44
20  21     URSULA     30
21  22   VINICIUS     25
22  23    WILLIAM     47
23  24     XAVIER     52
24  25     YASMIN     57
25  26     ZAQUEU     58
26  27     AMANDA     51
27  28   BERNARDO     20
28  29     CAMILA     33
29  30      DIEGO     53
30  31  JOÃO LUÍS     22

# Ex 12
Faça uma função que retorne o nome do funcionário com maior salário, unindo df_pessoas e df_funcionarios.

In [84]:
def funcionario_maior_salario(df_pessoas, df_funcionarios):
    df_merge = pd.merge(df_pessoas, df_funcionarios, on= "ID")
    linha_do_maior = df_merge["salario"].idxmax()
    maior_salario = df_merge.loc[linha_do_maior, "nome"].title()
    return maior_salario

resultado = funcionario_maior_salario(df_pessoas, df_funcionarios)
display(resultado)

'Sabrina'

# Ex 13
Escreva uma função que filtre df_funcionarios e retorne apenas funcionários do setor de TI.

In [87]:
def filtro_setor(df_funcionarios, nome_do_setor):
    df_filtrado = df_funcionarios[df_funcionarios["departamento"] == nome_do_setor]
    return df_filtrado
resultado = filtro_setor(df_funcionarios, "TI")
display(resultado)

    ID  salario departamento  Bonus
13  14     5952           TI  595.2
17  18     5876           TI  587.6
18  19     9919           TI  991.9
25  26     5668           TI  566.8
28  29     9401           TI  940.1

# Ex 14
Crie uma função que compare os salários reais de df_funcionarios com as médias de df_departamentos e indique quais estão acima da média do setor.

In [ ]:
def comparacao_salario_media(df_funcionarios, df_departamentos):
    df_merge = pd.merge(df_funcionarios, df_departamentos, on="departamento")
    df_acima = df_merge[df_merge["salario"] > df_merge["media_salario"]]
    return df_acima
resultado = comparacao_salario_media(df_funcionarios, df_departamentos)
display(resultado)

    ID  salario departamento  Bonus  media_salario
4    5     9581   Financeiro  958.1    6261.714286
5    6     9112           RH  911.2    7096.250000
6    7     9295       Vendas  929.5    7986.571429
7    8     8428    Marketing  842.8    6821.714286
10  11     8472       Vendas  847.2    7986.571429
14  15     7381   Financeiro  738.1    6261.714286
18  19     9919           TI  991.9    7363.200000
19  20     9720    Marketing  972.0    6821.714286
21  22     6551   Financeiro  655.1    6261.714286
22  23     9077       Vendas  907.7    7986.571429
23  24     6874    Marketing  687.4    6821.714286
26  27     6763   Financeiro  676.3    6261.714286
27  28     8744    Marketing  874.4    6821.714286
28  29     9401           TI  940.1    7363.200000

# Ex 15
Faça uma função que crie uma nova coluna em df_funcionarios indicando se o salário está acima ou abaixo da média do setor (baseando-se no df_departamentos).

In [98]:
def coluna_status(df_funcionarios, df_departamentos):
    df_merge = pd.merge(df_funcionarios, df_departamentos, on="departamento")

    df_merge["status"] = "Abaixo da Média"

    df_merge.loc[df_merge["salario"] == df_merge["media_salario"], "status"] = "Média"

    df_merge.loc[df_merge["salario"] > df_merge["media_salario"], "status"] = "Acima da Média"

    return df_merge
display(coluna_status(df_funcionarios, df_departamentos))

    ID  salario departamento  Bonus  media_salario           status
0    1     7019           RH  701.9    7096.250000  Abaixo da Média
1    2     7741       Vendas  774.1    7986.571429  Abaixo da Média
2    3     6498           RH  649.8    7096.250000  Abaixo da Média
3    4     4043    Marketing  404.3    6821.714286  Abaixo da Média
4    5     9581   Financeiro  958.1    6261.714286   Acima da Média
5    6     9112           RH  911.2    7096.250000   Acima da Média
6    7     9295       Vendas  929.5    7986.571429   Acima da Média
7    8     8428    Marketing  842.8    6821.714286   Acima da Média
8    9     6153       Vendas  615.3    7986.571429  Abaixo da Média
9   10     4815   Financeiro  481.5    6261.714286  Abaixo da Média
10  11     8472       Vendas  847.2    7986.571429   Acima da Média
11  12     7487       Vendas  748.7    7986.571429  Abaixo da Média
12  13     3540   Financeiro  354.0    6261.714286  Abaixo da Média
13  14     5952           TI  595.2    7363.200000  Abaixo da Média
14  15     7381   Financeiro  738.1    6261.714286   Acima da Média
15  16     7681       Vendas  768.1    7986.571429  Abaixo da Média
16  17     5756           RH  575.6    7096.250000  Abaixo da Média
17  18     5876           TI  587.6    7363.200000  Abaixo da Média
18  19     9919           TI  991.9    7363.200000   Acima da Média
19  20     9720    Marketing  972.0    6821.714286   Acima da Média
20  21     5201   Financeiro  520.1    6261.714286  Abaixo da Média
21  22     6551   Financeiro  655.1    6261.714286   Acima da Média
22  23     9077       Vendas  907.7    7986.571429   Acima da Média
23  24     6874    Marketing  687.4    6821.714286   Acima da Média
24  25     5866    Marketing  586.6    6821.714286  Abaixo da Média
25  26     5668           TI  566.8    7363.200000  Abaixo da Média
26  27     6763   Financeiro  676.3    6261.714286   Acima da Média
27  28     8744    Marketing  874.4    6821.714286   Acima da Média
28  29     9401           TI  940.1    7363.200000   Acima da Média
29  30     4077    Marketing  407.7    6821.714286  Abaixo da Média